---
- name: Verify pihole database dir
  ansible.builtin.file:
    path: "{{ pihole_database_volume }}"
    state: directory
    owner: "{{ docker_username }}"
    group: "{{ docker_main_group }}"
    mode: '0750'

- name: Verify pihole config dir
  ansible.builtin.file:
    path: "{{ pihole_config_volume }}"
    state: directory
    owner: "{{ docker_username }}"
    group: "{{ docker_main_group }}"
    mode: '0750'

- name: Verify dnsmasq config dir
  ansible.builtin.file:
    path: "{{ pihole_dnsmasq_config_volume }}"
    state: directory
    owner: "{{ docker_username }}"
    group: "{{ docker_main_group }}"
    mode: '0750'

- name: Set compose dir
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/{{ pihole_container_name }}"
    state: directory
    owner: "{{ docker_username }}"
    group: "{{ docker_main_group }}"
    mode: '0750'

- name: Set compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_dir }}/{{ pihole_container_name }}/docker-compose.yml"
    owner: "{{ docker_username }}"
    group: "{{ docker_main_group }}"
    mode: '0750'

- name: Run docker compose
  community.docker.docker_compose:
    project_src: "{{ docker_compose_dir }}/{{ pihole_container_name }}"
    pull: true
