---
- name: Verify config dir
  ansible.builtin.file:
    path: "{{ filebrowser_config_volume }}"
    state: directory
    owner: "{{ docker_username }}"
    group: "{{ docker_main_group }}"
    mode: '0750'

- name: Verify data dir
  ansible.builtin.file:
    path: "{{ filebrowser_data_volume }}"
    state: directory
    owner: "{{ docker_username }}"
    group: "{{ docker_main_group }}"
    mode: '0750'

- name: Set compose dir
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/{{ filebrowser_container_name }}"
    state: directory
    owner: "{{ docker_username }}"
    group: "{{ docker_main_group }}"
    mode: '0750'

- name: Set compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_dir }}/{{ filebrowser_container_name }}/docker-compose.yml"
    owner: "{{ docker_username }}"
    group: "{{ docker_main_group }}"
    mode: '0750'

- name: Run docker compose
  community.docker.docker_compose:
    project_src: "{{ docker_compose_dir }}/{{ filebrowser_container_name }}"
    pull: true
