---
- name: Check if module is already installed
  ansible.builtin.stat:
    path: "{{ module.dst_path }}"
  register: module_stat
  become: true
  become_user: "{{ base_user.username }}"

- name: Create tmpdir
  ansible.builtin.set_fact:
    tmpdir: "/tmp/{{ module.name }}"
  when: not module_stat.stat.exists
  become: true
  become_user: "{{ base_user.username }}"

- name: Clone the repository in a temp dir
  ansible.builtin.git:
    repo: "{{ module.repo }}"
    dest: "{{ tmpdir }}"
    version: "{{ module.version }}"
  when: not module_stat.stat.exists
  become: true
  become_user: "{{ base_user.username }}"

- name: Build command
  ansible.builtin.command:
    chdir: "{{ tmpdir }}"
    cmd: "{{ module.build_cmd }}"
  when: not module_stat.stat.exists
  become: true
  become_user: "{{ base_user.username }}"

- name: Remove the temp dir
  ansible.builtin.file:
    state: absent
    path: "{{ tmpdir }}"
  when: not module_stat.stat.exists
  become: true
  become_user: "{{ base_user.username }}"
