docker_repo_key_url: https://download.docker.com/linux/debian/gpg
docker_repo_url: https://download.docker.com/linux/debian
docker_key_file: /etc/apt/trusted.gpg.d/docker.gpg
docker_packages:
  - docker-ce
  - docker-ce-cli
  - docker-buildx-plugin
  - docker-compose-plugin
  - containerd.io
