---
- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: "{{ dotfiles_git_repo }}"
    dest: "{{ base_user.homedir }}/dotfiles"
    version: master
  become: true
  become_user: "{{ base_user.username }}"

- name: Stow config files
  ansible.builtin.shell: |
    cd "{{ base_user.homedir }}/dotfiles"
    git adopt --ignore default.png {{ item }}
    git restore .
    stow -t {{ base_user.homedir }} --ignore default.png {{ item }}
  become: true
  become_user: "{{ base_user.username }}"
  loop: "{{ dotfiles_stow_packages }}"
