---
- name: Enable archlinux multilib repository
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist
    marker: '# {mark} ANSIBLE MANAGED BLOCK - multilib'
    state: present
  become: yes
  notify: pacman_refresh

- name: Force handlers run
  meta: flush_handlers

- name: Install steam and dependencies packages
  community.general.pacman:
    name: "{{ steam_packages }}"
    state: present

- name: Install AUR packages
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: yay
    state: present
  become: true
  become_user: "{{ base_user.username }}"
  loop: "{{ steam_aur_packages }}"

- name: Install heroic flatpak
  community.general.flatpak:
    name: "{{ steam_heroic_flatpak }}"
    state: present
  become: true
  become_user: "{{ base_user.username }}"
  register: heroic_flatpak_install

- name: Override heroic filesystem
  ansible.builtin.command:
    cmd: flatpak override --user "{{ steam_heroic_flatpak }}" --filesystem="{{ steam_heroic_filesystem  }}"
  become: true
  become_user: "{{ base_user.username }}"
  when: heroic_flatpak_install.changed

- name: Create gamescope desktop entry
  ansible.builtin.copy:
    src: steam-big-picture.desktop
    dest: /usr/share/wayland-sessions/steam-big-picture.desktop
    owner: root
    group: root
    mode: '0755'
