---
steam_packages:
  - flatpak
  - gamescope
  - lib32-mangohud
  - lib32-mesa
  - lib32-pipewire
  - lib32-vulkan-radeon
  - mangohud
  - mesa
  - steam
  - ttf-liberation
  - vulkan-radeon

steam_aur_packages:
  - gamescope-session-steam-git

steam_heroic_flatpak: com.heroicgameslauncher.hgl
steam_heroic_filesystem: /data/heroic
