---
- name: Verify mosquitto base dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ docker_username }}"
    group: "{{ docker_main_group }}"
    mode: '0750'
  loop:
    - "{{ mosquitto_data_volume }}"
    - "{{ mosquitto_config_volume }}"

- name: Verify mosquitto configuration file
  ansible.builtin.template:
    src: mosquitto.conf.j2
    dest: "{{ mosquitto_config_file }}"
    owner: "{{ docker_username }}"
    group: "{{ docker_main_group }}"
    mode: '0750'

- name: Verify mosquitto password file
  ansible.builtin.template:
    src: passwordfile.j2
    dest: "{{ mosquitto_password_file }}"
    owner: "{{ docker_username }}"
    group: "{{ docker_main_group }}"
    mode: '0750'

- name: Set and run docker compose
  ansible.builtin.include_role:
    name: docker
    tasks_from: docker-compose
  vars:
    docker_container_name: "{{ mosquitto_container_name }}"
