---
- name: Archlinux configuration playbook
  hosts: all
  gather_facts: true
  become: true

  roles:
    - base
    # - extra
    # - laptop
    # - dev
    # - dotfiles
    # - window_manager
    - steam
