---
- name: Verify uptime-kuma data dir
  ansible.builtin.file:
    path: "{{ uptime_kuma_data_volume }}"
    state: directory
    owner: "{{ docker_username }}"
    group: "{{ docker_main_group }}"
    mode: '0750'

- name: Set and run docker compose
  ansible.builtin.include_role:
    name: docker
    tasks_from: docker-compose
  vars:
    docker_container_name: "{{ uptime_kuma_container_name }}"
