---
- name: Install docker packages
  ansible.builtin.include_tasks: tasks/docker-packages.yml
  when: docker_install_packages

- name: Add docker user
  ansible.builtin.user:
    name: "{{ docker_username }}"
    groups: "{{ docker_groups }}"

- name: Get docker user
  ansible.builtin.user:
    name: "{{ docker_username }}"
  check_mode: true
  register: docker_user_obj

- name: Set docker uid fact
  ansible.builtin.set_fact:
    docker_user_uid: "{{ docker_user_obj.uid }}"

- name: Get docker group
  ansible.builtin.group:
    name: "{{ docker_main_group }}"
  check_mode: true
  register: docker_group_obj

- name: Set docker gid fact
  ansible.builtin.set_fact:
    docker_group_gid: "{{ docker_group_obj.gid }}"

- name: Enable and start docker service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started

- name: Set main dirs and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ docker_username }}"
    group: "{{ docker_main_group }}"
    mode: '0750'
  with_items: "{{ docker_dirs }}"
