---
- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: "{{ dotfiles_git_repo }}"
    dest: /tmp/dotfiles
    version: master
  become: true
  become_user: "{{ base_user.username }}"

- name: Synchronise dotfiles into user home
  ansible.posix.synchronize:
    src: "/tmp/dotfiles/{{ dotfiles_git_repo_subdir }}/"
    dest: "{{ base_user.homedir }}/"
  delegate_to: "{{ inventory_hostname }}"
  become: true
  become_user: "{{ base_user.username }}"
